x-common-app-config: &common-app-config
  volumes:
    - ./data:/app/data
  env_file:
    - .key       
  command: ["--matcher", "70", "--speed", "1"]      
  restart: "no"
  network_mode: host        

services:
  linkedin-dev:
    build:
      target: dev
      dockerfile: dockerfile
    <<: *common-app-config       
    volumes:
      - ./:/app 
    command: ["python", "src/linkedin.py", "--matcher", "60", "--speed", "1"]      
    profiles:
      - dev
      
  linkedin-final:
    image: testlabz/linkedin-pw
    <<: *common-app-config        
    profiles:
      - final
