# Usage:

x-common-app-config: &common-app-config
  image: varlabz/linkedin-pw
  volumes:
    - ./:/app/data
  env_file:
    - .key       
  restart: "no"
  network_mode: host        
  profiles:
    - final

x-common-app-config-dev: &common-app-config-dev
  build:
    target: dev
    dockerfile: dockerfile
  volumes:
    - ./:/app/
  env_file:
    - .key       
  restart: "no"
  network_mode: host        
  profiles:
    - dev

services:
# dev services     
  dev:
    <<: *common-app-config-dev       
    command: ["python", "-u", "src/linkedin.py", "--click-apply", "--click-easy-apply", "--matcher", "70", "--speed", "1", "--debug-1page"]      

# prod services     
  run:
    <<: *common-app-config        
    command: ["python", "-u", "src/linkedin.py", "--click-apply", "--click-easy-apply", "--matcher", "70", "--speed", "1"]      

  run-1-page:
    <<: *common-app-config        
    command: ["python", "-u", "src/linkedin.py", "--click-apply", "--click-easy-apply", "--matcher", "70", "--speed", "1", "--debug-1page",]      
    
  run-try:
    <<: *common-app-config        
    command: ["python", "-u", "src/linkedin.py", "--matcher", "70", "--speed", "1", "--debug-1page",]      

  run-job:
    <<: *common-app-config      
    environment:
      JOB: ${JOB:-''}
    command: ["python", "-u", "src/chat.py", "-j", "data/${JOB:-'create file with job description'}"]      
