# Usage:
# To start the services with image from docker repo, run:
#   docker compose --profile final up
#
# To build and start the services with the dev profile and use code from local directory, run:
#   docker compose --profile dev up
#

x-common-app-config: &common-app-config
  volumes:
    - ./data:/app/data
  env_file:
    - .key       
  command: ["--click-apply", "--click-easy-apply", "--matcher", "70", "--speed", "1"]      
  restart: "no"
  network_mode: host        

services:
  linkedin-dev:
    build:
      target: dev
      dockerfile: dockerfile
    <<: *common-app-config       
    volumes:
      - ./:/app 
    command: ["python", "-u", "src/linkedin.py", "--click-apply", "--click-easy-apply", "--matcher", "60", "--speed", "1", "--debug-1page"]      
    profiles:
      - dev
      
  linkedin-final:
    image: varlabz/linkedin-pw
    <<: *common-app-config        
    profiles:
      - final
